### ISSUE TITLE
There are a lot of bugs because of version outdated for example code about federated learning. Reading the book is a waste of time.

### ISSUE THREAD

**Issue by woxinguangming** [PacktPublishing/Machine-Learning-for-Cybersecurity-Cookbook#14]

**Comment by rajat-packt** [comment]
Hey @woxinguangming  this book was published in 2019, there are bound to be somethings that get outdated in the span of 2 years.
But, if you can provide details regarding the issues that you are facing we can try contacting the author and getting them to resolve your queries.
