### ISSUE TITLE
Scraping GitHub for files of a specific type. 

### ISSUE THREAD

**Issue by d0uble3L** [PacktPublishing/Machine-Learning-for-Cybersecurity-Cookbook#8]
Where can I find the accompanying repository that has the Powershell, Python, and Javascript zip files?

**Comment by ManikandanKurup-Packt** [comment]
Hi @d0uble3L,
It's in the [Classifying Files by Type](https://github.com/PacktPublishing/Machine-Learning-for-Cybersecurity-Cookbook/tree/master/Chapter02/Classifying%20Files%20by%20Type) folder.
